version: "3"

services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./docker-volumes/mariadb:/var/lib/mysql

  ############
  # Metabase #
  ############

  metabase:
      image: metabase/metabase
      ports:
        - 3000:3000
      depends_on:
        - metabase-postgres
      environment:
        MB_DB_TYPE: postgres
        MB_DB_DBNAME: metabase
        MB_DB_PORT: 5432
        MB_DB_USER: user
        MB_DB_PASS: password
        MB_DB_HOST: metabase-postgres

  metabase-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: metabase
    volumes:
      - ./docker-volumes/metabase-postgres:/var/lib/postgresql/data/

  ###########
  # Airflow #
  ###########

  airflow-redis:
        image: 'redis:3.2.7'
        # command: redis-server --requirepass redispass

  airflow-postgres:
      image: postgres:9.6
      environment:
          - POSTGRES_USER=airflow
          - POSTGRES_PASSWORD=airflow
          - POSTGRES_DB=airflow
      volumes:
        - ./docker-volumes/airflow-postgres:/var/lib/postgresql/data/

  airflow-webserver:
      image: puckel/docker-airflow:1.10.3
      restart: always
      depends_on:
          - airflow-postgres
          - airflow-redis
      environment:
          - LOAD_EX=n
          - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
          - EXECUTOR=Celery
          - POSTGRES_HOST=airflow-postgres
          - REDIS_HOST=airflow-redis
          - PYTHONPATH=${PYTHONPATH}:/opt
          # - POSTGRES_USER=airflow
          # - POSTGRES_PASSWORD=airflow
          # - POSTGRES_DB=airflow
          # - REDIS_PASSWORD=redispass
      volumes:
          - ./dags:/usr/local/airflow/dags
          # Uncomment to include custom plugins
          # - ./plugins:/usr/local/airflow/plugins
          - ./python_package:/opt/python_package/
      ports:
          - "8080:8080"
      command: webserver
      healthcheck:
          test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
          interval: 30s
          timeout: 30s
          retries: 3

  flower:
      image: puckel/docker-airflow:1.10.3
      restart: always
      depends_on:
          - airflow-redis
      environment:
          - EXECUTOR=Celery
          - REDIS_HOST=airflow-redis
          - POSTGRES_HOST=airflow-postgres
          # - REDIS_PASSWORD=redispass
      ports:
          - "5555:5555"
      command: flower

  airflow-scheduler:
      image: puckel/docker-airflow:1.10.3
      restart: always
      depends_on:
          - airflow-webserver
      volumes:
          - ./dags:/usr/local/airflow/dags
          # Uncomment to include custom plugins
          # - ./plugins:/usr/local/airflow/plugins
          - ./python_package:/opt/python_package/
      environment:
          - LOAD_EX=n
          - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
          - EXECUTOR=Celery
          - POSTGRES_HOST=airflow-postgres
          - REDIS_HOST=airflow-redis
          - PYTHONPATH=${PYTHONPATH}:/opt
          # - POSTGRES_USER=airflow
          # - POSTGRES_PASSWORD=airflow
          # - POSTGRES_DB=airflow
          # - REDIS_PASSWORD=redispass
      command: scheduler

  worker:
      image: puckel/docker-airflow:1.10.3
      restart: always
      depends_on:
          - airflow-scheduler
      volumes:
          - ./dags:/usr/local/airflow/dags
          # Uncomment to include custom plugins
          # - ./plugins:/usr/local/airflow/plugins
          - ./python_package:/opt/python_package/
      environment:
          - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
          - EXECUTOR=Celery
          - POSTGRES_HOST=airflow-postgres
          - REDIS_HOST=airflow-redis
          - PYTHONPATH=${PYTHONPATH}:/opt
          # - POSTGRES_USER=airflow
          # - POSTGRES_PASSWORD=airflow
          # - POSTGRES_DB=airflow
          # - REDIS_PASSWORD=redispass
      command: worker
